## Installs

In [ ]:
%%capture
!pip install transformers
!pip install git+https://github.com/csebuetnlp/normalizer

## Preprocessing

In [ ]:
import pandas as pd

df = pd.read_csv("./Data/Training Data/split600K.csv")
df

,bn_Keywords,bn_Sentence
0,"['হ্যামিল্টনেও', 'কিছু', 'হয়নি', 'ব্যতিক্রম']",হ্যামিল্টনেও এর ব্যতিক্রম কিছু হয়নি।
1,"['কঠিন', 'গ্রুপে', 'খুবই', 'এক', 'বাংলাদেশ']",যেমন এবার বাংলাদেশ পড়েছে খুবই কঠিন এক গ্রুপে।
2,"['নকিপুর', 'কেন্দ্রের', 'সরকারি', 'সাংসদ', 'বি...",গতকাল সকাল সাড়ে ১০টার দিকে নকিপুর সরকারি প্রাথ...
3,"['শফিউল', 'নয়াদিল্লিতে', 'মুহাম্মদ', 'হকের', ...",খবর এনডিটিভির।নয়াদিল্লিতে বাংলাদেশের সেনাপ্রধা...
4,"['ঝুলে', 'আছে', 'গ্রামে', 'বিভিন্ন', 'তাঁদের',...","কারণ, এখনো ইউনিয়নের বিভিন্ন গ্রামে তাঁদের পোস্..."
...,...,...
199997,"['হ্যালোইন', 'অক্টোবরের', 'যাকে', 'দিন', 'আমের...",মনে রাখতে হবে অক্টোবরের ৩১ তারিখ হলো আমেরিকানদ...
199998,"['মিসরে', 'গণতন্ত্র', 'কথা', 'এল', 'বলে', 'সরি...","মিসরে গণতন্ত্র এল, কী এক কথা বলে তাদের সরিয়ে ..."
199999,"['পানীয়ের', 'দোকানগুলো', 'বন্ধ', 'নির্দেশ']",পানীয়ের দোকানগুলো বন্ধ রাখার নির্দেশ দেওয়া হয়েছে।
200000,"['মামলা', 'আছে', 'তাঁর', 'বিরুদ্ধে']",তাঁর বিরুদ্ধে অন্তত ১১টি মামলা আছে।
200001,"['ইনিংস', 'জিম্বাবুয়ের', 'সর্বশেষ', 'হয়তো', ...","যেমনটা শুনেছি, এটিই হয়তো জিম্বাবুয়ের হয়ে তা..."

### Clean Special Characters and Others

In [ ]:
import string
invalidcharacters= set(string.punctuation)

def invalidcharacter(key):
    if key in invalidcharacters:
        return True
    else:
        return False

In [ ]:
def cleanDataX(keywords):

  strs = ''
  Flag = 0
  for i in range(len(keywords)):

    if keywords[i] == '[':
      continue
    elif keywords[i] ==']':
      continue
    elif keywords[i] =='।': # dari
      continue
    elif keywords[i] =='‘': # 4278
      continue
    elif keywords[i] =='’': # 4278
      continue
    elif keywords[i] == chr(39): # '
      continue
    elif keywords[i] == chr(44): # ,
      continue
    # elif checkEnglish(keywords[i]) == True and invalidcharacter(keywords[i]) == True:
    #   continue
    elif invalidcharacter(keywords[i]) == True:
      continue
    else:
      strs = strs + keywords[i]

  # return ''.join((x for x in strs if not x.isdigit()))
  return ''.join(strs)

df['bn_Keywords'] = df['bn_Keywords'].apply(cleanDataX)

df.to_csv("./Data/Training Data/split600K.csv", index=False)

### Clean English Alphabet

In [ ]:
df

,bn_Keywords,bn_Sentence
0,হ্যামিল্টনেও কিছু হয়নি ব্যতিক্রম,হ্যামিল্টনেও এর ব্যতিক্রম কিছু হয়নি।
1,কঠিন গ্রুপে খুবই এক বাংলাদেশ,যেমন এবার বাংলাদেশ পড়েছে খুবই কঠিন এক গ্রুপে।
2,নকিপুর কেন্দ্রের সরকারি সাংসদ বিদ্যালয় মারধর ...,গতকাল সকাল সাড়ে ১০টার দিকে নকিপুর সরকারি প্রাথ...
3,শফিউল নয়াদিল্লিতে মুহাম্মদ হকের বেলাল খবর আবু...,খবর এনডিটিভির।নয়াদিল্লিতে বাংলাদেশের সেনাপ্রধা...
4,ঝুলে আছে গ্রামে বিভিন্ন তাঁদের ইউনিয়নের,"কারণ, এখনো ইউনিয়নের বিভিন্ন গ্রামে তাঁদের পোস্..."
...,...,...
199997,হ্যালোইন অক্টোবরের যাকে দিন আমেরিকানদের ৩১ বলে...,মনে রাখতে হবে অক্টোবরের ৩১ তারিখ হলো আমেরিকানদ...
199998,মিসরে গণতন্ত্র কথা এল বলে সরিয়ে তাদের,"মিসরে গণতন্ত্র এল, কী এক কথা বলে তাদের সরিয়ে ..."
199999,পানীয়ের দোকানগুলো বন্ধ নির্দেশ,পানীয়ের দোকানগুলো বন্ধ রাখার নির্দেশ দেওয়া হয়েছে।
200000,মামলা আছে তাঁর বিরুদ্ধে,তাঁর বিরুদ্ধে অন্তত ১১টি মামলা আছে।
200001,ইনিংস জিম্বাবুয়ের সর্বশেষ হয়তো শুনেছি এটিই,"যেমনটা শুনেছি, এটিই হয়তো জিম্বাবুয়ের হয়ে তা..."

In [ ]:
import csv
import re

# Open the CSV file and create a reader object with 'utf-8' encoding
with open("./Data/Training Data/split600K.csv", 'r', encoding='utf-8') as file:
    reader = csv.reader(file)

    # Get the header row and find the index of the specific column
    header = next(reader)
    column_index = header.index('bn_Sentence')

    # Create a new list to hold the rows that don't contain English words
    clean_rows = []

    # Loop through each row in the file
    for row in reader:

        # Check if the specific column contains any English words
        if not re.search(r'[a-zA-Z0-9]', row[column_index]):

            # If there are no English words, add the row to the clean_rows list
            clean_rows.append(row)

    # Write the clean rows to a new CSV file
    with open('./Data/Training Data/split600K.csv', 'w', newline='', encoding='utf-8') as clean_file:
        writer = csv.writer(clean_file)
        writer.writerow(header)
        writer.writerows(clean_rows)

In [ ]:
up_df = pd.read_csv('./Data/Training Data/split600K.csv')
up_df

,bn_Keywords,bn_Sentence
0,হ্যামিল্টনেও কিছু হয়নি ব্যতিক্রম,হ্যামিল্টনেও এর ব্যতিক্রম কিছু হয়নি।
1,কঠিন গ্রুপে খুবই এক বাংলাদেশ,যেমন এবার বাংলাদেশ পড়েছে খুবই কঠিন এক গ্রুপে।
2,নকিপুর কেন্দ্রের সরকারি সাংসদ বিদ্যালয় মারধর ...,গতকাল সকাল সাড়ে ১০টার দিকে নকিপুর সরকারি প্রাথ...
3,শফিউল নয়াদিল্লিতে মুহাম্মদ হকের বেলাল খবর আবু...,খবর এনডিটিভির।নয়াদিল্লিতে বাংলাদেশের সেনাপ্রধা...
4,ঝুলে আছে গ্রামে বিভিন্ন তাঁদের ইউনিয়নের,"কারণ, এখনো ইউনিয়নের বিভিন্ন গ্রামে তাঁদের পোস্..."
...,...,...
199997,হ্যালোইন অক্টোবরের যাকে দিন আমেরিকানদের ৩১ বলে...,মনে রাখতে হবে অক্টোবরের ৩১ তারিখ হলো আমেরিকানদ...
199998,মিসরে গণতন্ত্র কথা এল বলে সরিয়ে তাদের,"মিসরে গণতন্ত্র এল, কী এক কথা বলে তাদের সরিয়ে ..."
199999,পানীয়ের দোকানগুলো বন্ধ নির্দেশ,পানীয়ের দোকানগুলো বন্ধ রাখার নির্দেশ দেওয়া হয়েছে।
200000,মামলা আছে তাঁর বিরুদ্ধে,তাঁর বিরুদ্ধে অন্তত ১১টি মামলা আছে।
200001,ইনিংস জিম্বাবুয়ের সর্বশেষ হয়তো শুনেছি এটিই,"যেমনটা শুনেছি, এটিই হয়তো জিম্বাবুয়ের হয়ে তা..."

In [ ]:
up_df.isnull().sum()

bn_Keywords    9
bn_Sentence    0
dtype: int64

In [ ]:
up_df.dropna(inplace=True)

In [ ]:
up_df = up_df.reset_index()

In [ ]:
up_df.isnull().sum()

index          0
bn_Keywords    0
bn_Sentence    0
dtype: int64

In [ ]:
up_df = up_df.drop(columns=['index'])
up_df

,bn_Keywords,bn_Sentence
0,হ্যামিল্টনেও কিছু হয়নি ব্যতিক্রম,হ্যামিল্টনেও এর ব্যতিক্রম কিছু হয়নি।
1,কঠিন গ্রুপে খুবই এক বাংলাদেশ,যেমন এবার বাংলাদেশ পড়েছে খুবই কঠিন এক গ্রুপে।
2,নকিপুর কেন্দ্রের সরকারি সাংসদ বিদ্যালয় মারধর ...,গতকাল সকাল সাড়ে ১০টার দিকে নকিপুর সরকারি প্রাথ...
3,শফিউল নয়াদিল্লিতে মুহাম্মদ হকের বেলাল খবর আবু...,খবর এনডিটিভির।নয়াদিল্লিতে বাংলাদেশের সেনাপ্রধা...
4,ঝুলে আছে গ্রামে বিভিন্ন তাঁদের ইউনিয়নের,"কারণ, এখনো ইউনিয়নের বিভিন্ন গ্রামে তাঁদের পোস্..."
...,...,...
199988,হ্যালোইন অক্টোবরের যাকে দিন আমেরিকানদের ৩১ বলে...,মনে রাখতে হবে অক্টোবরের ৩১ তারিখ হলো আমেরিকানদ...
199989,মিসরে গণতন্ত্র কথা এল বলে সরিয়ে তাদের,"মিসরে গণতন্ত্র এল, কী এক কথা বলে তাদের সরিয়ে ..."
199990,পানীয়ের দোকানগুলো বন্ধ নির্দেশ,পানীয়ের দোকানগুলো বন্ধ রাখার নির্দেশ দেওয়া হয়েছে।
199991,মামলা আছে তাঁর বিরুদ্ধে,তাঁর বিরুদ্ধে অন্তত ১১টি মামলা আছে।
199992,ইনিংস জিম্বাবুয়ের সর্বশেষ হয়তো শুনেছি এটিই,"যেমনটা শুনেছি, এটিই হয়তো জিম্বাবুয়ের হয়ে তা..."

In [ ]:
up_df.isnull().sum()

bn_Keywords    0
bn_Sentence    0
dtype: int64

In [ ]:
up_df.to_csv("./Data/Training Data/split600K.csv", index=False)